#!/usr/bin/env bash

set -e

[[ ! -z "$SUDO_USER" ]] && user=$SUDO_USER || user=$LOGNAME

DATA_PATH=${1:-/opt/cathook/data}

if [ "$EUID" != 0 ]; then
    exec sudo "$0" "$@"
fi

if ! [ -d "$DATA_PATH" ]; then
    echo "Creating cathook data directory at $DATA_PATH"
    mkdir -p "$DATA_PATH"
    chown -R "$user" "$DATA_PATH"
    chmod -R 774 "$DATA_PATH"
fi

echo "Installing cathook data to $DATA_PATH"
rsync -avh "data/" "$DATA_PATH"
rsync -avh --ignore-existing "config_data/" "$DATA_PATH"
chown -R "$user" "$DATA_PATH"
chmod -R 774 "$DATA_PATH"
