#!/usr/bin/env bash

set -e

#
#

proccount=$(grep -c '^processor' /proc/cpuinfo)
mkdir -p build
pushd build >/dev/null
cmake ..
cmake --build . --target cathook -- -j"$proccount"
popd >/dev/null

./install-data
